# Generated by Django 5.2 on 2025-11-02 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="student",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_groups",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="students.studentgroup"
            ),
        ),
        migrations.RemoveField(
            model_name="student",
            name="student_group",
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("organization", "user")},
        ),
    ]
