# Generated by Django 5.2 on 2025-11-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        (
            "students",
            "0002_alter_student_unique_together_student_student_groups_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentgroup",
            name="module",
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="modules",
            field=models.ManyToManyField(
                blank=True, related_name="student_groups", to="courses.module"
            ),
        ),
    ]
