# Generated by Django 5.2 on 2025-11-09 13:36

import django.db.models.deletion
from django.db import migrations, models
from django.contrib.contenttypes.models import ContentType


def migrate_question_to_generic(apps, schema_editor):
    """Migrate existing question ForeignKey to GenericForeignKey."""
    StudentQuestionAnswer = apps.get_model('students', 'StudentQuestionAnswer')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Get the ContentType for MultipleChoiceQuestion (which Question becomes)
    # Note: After quizzes migration, Question becomes MultipleChoiceQuestion
    try:
        mcq_content_type = ContentType.objects.get(
            app_label='quizzes',
            model='multiplechoicequestion'
        )
    except ContentType.DoesNotExist:
        # Fallback: try 'question' if migration hasn't run yet
        try:
            mcq_content_type = ContentType.objects.get(
                app_label='quizzes',
                model='question'
            )
        except ContentType.DoesNotExist:
            # If neither exists, skip migration (no data to migrate)
            return
    
    # Migrate all existing StudentQuestionAnswer records
    # The old question field is now named question_old after RenameField
    for answer in StudentQuestionAnswer.objects.filter(question_content_type__isnull=True):
        if hasattr(answer, 'question_old') and answer.question_old:
            # Copy the question ID from the old field
            answer.question_id = answer.question_old_id
            answer.question_content_type = mcq_content_type
            answer.save()


def reverse_migrate_question(apps, schema_editor):
    """Reverse migration - not fully reversible but prevents errors."""
    # This is a one-way migration, so we'll just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0001_initial"),
        ("quizzes", "0004_migrate_to_generic_question"),
        ("students", "0003_remove_studentgroup_module_studentgroup_modules"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentquestionanswer",
            unique_together=set(),  # Remove old constraint temporarily
        ),
        migrations.AddField(
            model_name="studentquestionanswer",
            name="answer_data",
            field=models.JSONField(blank=True, null=True),
        ),
        # Rename the old question_id column to avoid conflict
        migrations.RenameField(
            model_name="studentquestionanswer",
            old_name="question",
            new_name="question_old",
        ),
        # Now add the new GenericForeignKey fields
        migrations.AddField(
            model_name="studentquestionanswer",
            name="question_content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "model__in": [
                        "multiplechoicequestion",
                        "orderquestion",
                        "connectquestion",
                    ]
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="studentquestionanswer",
            name="question_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentquestionanswer",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_selections",
                to="quizzes.option",
            ),
        ),
        # Data migration: populate new fields from old question_old field
        migrations.RunPython(migrate_question_to_generic, reverse_migrate_question),
        # Now remove the old question_old field (which was renamed from question)
        migrations.RemoveField(
            model_name="studentquestionanswer",
            name="question_old",
        ),
        # Restore unique constraint with new fields
        migrations.AlterUniqueTogether(
            name="studentquestionanswer",
            unique_together={
                (
                    "organization",
                    "student",
                    "question_content_type",
                    "question_id",
                    "quiz",
                )
            },
        ),
    ]
