# Generated by Django 5.2 on 2025-11-24 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("students", "0004_migrate_to_generic_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentquestionanswer",
            name="question_content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "model__in": [
                        "multiplechoicequestion",
                        "orderquestion",
                        "connectquestion",
                        "numberquestion",
                    ]
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
