# Generated by Django 5.2 on 2025-10-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_quiz_question_quiz"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
