# Generated by Django 5.2 on 2025-11-09 13:36

import django.db.models.deletion
from django.db import migrations, models


def migrate_questions_to_multiplechoice(apps, schema_editor):
    """Migrate existing Question records to MultipleChoiceQuestion BEFORE removing fields."""
    Question = apps.get_model('quizzes', 'Question')
    MultipleChoiceQuestion = apps.get_model('quizzes', 'MultipleChoiceQuestion')
    Option = apps.get_model('quizzes', 'Option')
    
    # Copy all Question records to MultipleChoiceQuestion
    # This must happen BEFORE the fields are removed from Question
    for question in Question.objects.all():
        # Get all related data while fields still exist
        learning_objectives = list(question.learning_objectives.all())
        
        # Create MultipleChoiceQuestion with same data
        mcq = MultipleChoiceQuestion.objects.create(
            id=question.id,  # Preserve the same ID
            text=question.text,
            order=question.order,
            organization=question.organization,
            topic=question.topic,
            quiz=question.quiz,
            question_type='multiple_choice',
            created_at=question.created_at,
            updated_at=question.updated_at,
        )
        
        # Restore many-to-many relationships
        mcq.learning_objectives.set(learning_objectives)
        
        # Update all Option records to point to the new MultipleChoiceQuestion
        # This preserves the foreign key relationships
        Option.objects.filter(question_id=question.id).update(question_id=mcq.id)


def reverse_migrate(apps, schema_editor):
    """Reverse migration - not fully reversible."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("organizations", "0001_initial"),
        ("quizzes", "0003_alter_question_options_question_order"),
    ]

    operations = [
        # Add image field to Option
        migrations.AddField(
            model_name="option",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="options/"),
        ),
        # Create all new question type models
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("order", "Order"),
                            ("connect", "Connect"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="questions/"),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="questions/videos/"
                    ),
                ),
                (
                    "learning_objectives",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_questions",
                        to="courses.learningobjective",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_questions",
                        to="quizzes.quiz",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_questions",
                        to="courses.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("order", "Order"),
                            ("connect", "Connect"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="questions/"),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="questions/videos/"
                    ),
                ),
                (
                    "learning_objectives",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_questions",
                        to="courses.learningobjective",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_questions",
                        to="quizzes.quiz",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_questions",
                        to="courses.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="order_options/"
                    ),
                ),
                (
                    "correct_order",
                    models.PositiveIntegerField(
                        help_text="The correct position in the order (1-based)"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_options",
                        to="quizzes.orderquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["correct_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ConnectQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("order", "Order"),
                            ("connect", "Connect"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="questions/"),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="questions/videos/"
                    ),
                ),
                (
                    "learning_objectives",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_questions",
                        to="courses.learningobjective",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_questions",
                        to="quizzes.quiz",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_questions",
                        to="courses.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConnectOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="connect_options/"
                    ),
                ),
                ("position_x", models.FloatField(help_text="X position (0.0 to 1.0)")),
                ("position_y", models.FloatField(help_text="Y position (0.0 to 1.0)")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connect_options",
                        to="quizzes.connectquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ConnectOptionConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_from",
                        to="quizzes.connectoption",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "to_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_to",
                        to="quizzes.connectoption",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correct_connections",
                        to="quizzes.connectquestion",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("organization", "question", "from_option", "to_option")
                },
            },
        ),
        # Migrate data BEFORE removing fields from Question
        migrations.RunPython(migrate_questions_to_multiplechoice, reverse_migrate),
        # Now update Option to point to MultipleChoiceQuestion
        migrations.AlterField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="quizzes.multiplechoicequestion",
            ),
        ),
        # Now we can safely remove fields from Question
        migrations.RemoveField(
            model_name="question",
            name="learning_objectives",
        ),
        migrations.RemoveField(
            model_name="question",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="question",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="question",
            name="topic",
        ),
    ]
