# Generated by Django 5.2 on 2025-11-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0004_migrate_to_generic_question"),
        ("students", "0004_migrate_to_generic_question"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Question",
        ),
    ]
