# Generated by Django 5.2 on 2025-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0005_migrate_to_generic_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
            },
        ),
        migrations.AddField(
            model_name="connectoption",
            name="height",
            field=models.FloatField(default=60.0, help_text="Height in pixels"),
        ),
        migrations.AddField(
            model_name="connectoption",
            name="width",
            field=models.FloatField(default=100.0, help_text="Width in pixels"),
        ),
    ]
