# Generated by Django 5.2 on 2025-11-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0006_alter_quiz_options_connectoption_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectoption",
            name="hide_text",
            field=models.BooleanField(
                default=False,
                help_text="If True, hide the text and use it as alt-text for the image (for accessibility)",
            ),
        ),
        migrations.AddField(
            model_name="connectquestion",
            name="hide_text",
            field=models.BooleanField(
                default=False,
                help_text="If True, hide the text and use it as alt-text for the image (for accessibility)",
            ),
        ),
        migrations.AddField(
            model_name="multiplechoicequestion",
            name="hide_text",
            field=models.BooleanField(
                default=False,
                help_text="If True, hide the text and use it as alt-text for the image (for accessibility)",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="hide_text",
            field=models.BooleanField(
                default=False,
                help_text="If True, hide the text and use it as alt-text for the image (for accessibility)",
            ),
        ),
        migrations.AddField(
            model_name="orderoption",
            name="hide_text",
            field=models.BooleanField(
                default=False,
                help_text="If True, hide the text and use it as alt-text for the image (for accessibility)",
            ),
        ),
        migrations.AddField(
            model_name="orderquestion",
            name="hide_text",
            field=models.BooleanField(
                default=False,
                help_text="If True, hide the text and use it as alt-text for the image (for accessibility)",
            ),
        ),
    ]
