# Generated by Django 5.2 on 2025-11-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("organizations", "0001_initial"),
        ("quizzes", "0007_connectoption_hide_text_connectquestion_hide_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("order", "Order"),
                    ("connect", "Connect"),
                    ("number", "Number"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="multiplechoicequestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("order", "Order"),
                    ("connect", "Connect"),
                    ("number", "Number"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("order", "Order"),
                    ("connect", "Connect"),
                    ("number", "Number"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NumberQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("order", "Order"),
                            ("connect", "Connect"),
                            ("number", "Number"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="questions/"),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="questions/videos/"
                    ),
                ),
                (
                    "hide_text",
                    models.BooleanField(
                        default=False,
                        help_text="If True, hide the text and use it as alt-text for the image (for accessibility)",
                    ),
                ),
                (
                    "correct_answer",
                    models.FloatField(help_text="The correct numeric answer"),
                ),
                (
                    "tolerance",
                    models.FloatField(
                        default=0.0,
                        help_text="Tolerance for the answer (e.g., 0.1 means answer is correct if within ±0.1 of correct_answer)",
                    ),
                ),
                (
                    "learning_objectives",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_questions",
                        to="courses.learningobjective",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_questions",
                        to="quizzes.quiz",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_questions",
                        to="courses.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "abstract": False,
            },
        ),
    ]
