# Generated by Django 5.2 on 2025-11-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0008_alter_connectquestion_question_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectquestion",
            name="learning_objectives",
        ),
        migrations.RemoveField(
            model_name="multiplechoicequestion",
            name="learning_objectives",
        ),
        migrations.RemoveField(
            model_name="numberquestion",
            name="learning_objectives",
        ),
        migrations.RemoveField(
            model_name="orderquestion",
            name="learning_objectives",
        ),
    ]
