# Generated by Django 5.2 on 2025-11-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0009_remove_connectquestion_learning_objectives_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectoption",
            name="connectable",
            field=models.BooleanField(
                default=True,
                help_text="If True, connections can be made to and from this option",
            ),
        ),
    ]
