# Generated by Django 5.2 on 2025-11-24 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_presentation_reader"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reader",
            name="course",
        ),
        migrations.RemoveField(
            model_name="reader",
            name="learning_objectives",
        ),
        migrations.RemoveField(
            model_name="reader",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="reader",
            name="module",
        ),
        migrations.RemoveField(
            model_name="reader",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="reader",
            name="topic",
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("reader", "Reader"),
                            ("presentation", "Presentation"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload a file (PDF, DOCX, PPTX, etc.)",
                        null=True,
                        upload_to="materials/",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Rich text content (HTML or Markdown)"
                    ),
                ),
                (
                    "slide_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of slides in the presentation",
                        null=True,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="courses.course",
                    ),
                ),
                (
                    "learning_objectives",
                    models.ManyToManyField(
                        blank=True,
                        related_name="materials",
                        to="courses.learningobjective",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="courses.lesson",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="courses.module",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="courses.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Presentation",
        ),
        migrations.DeleteModel(
            name="Reader",
        ),
    ]
