# Generated by Django 5.2 on 2025-11-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_remove_reader_course_and_more"),
        ("quizzes", "0009_remove_connectquestion_learning_objectives_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="learning_objectives",
        ),
        migrations.DeleteModel(
            name="LearningObjective",
        ),
    ]
