# Generated by Django 5.2 on 2025-11-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_remove_material_learning_objectives_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="material",
            name="module",
        ),
        migrations.RemoveField(
            model_name="material",
            name="topic",
        ),
        migrations.AddField(
            model_name="material",
            name="lessons",
            field=models.ManyToManyField(
                blank=True, related_name="materials", to="courses.lesson"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="modules",
            field=models.ManyToManyField(
                blank=True, related_name="materials", to="courses.module"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="materials", to="courses.topic"
            ),
        ),
    ]
